### ISSUE TITLE
not locally

### ISSUE THREAD

**Issue by Badaryman** [Kenimarru/hiruki#2]
not locally

_Originally posted by @Badaryman in https://github.com/Kenimarru/hiruki/issues/1#issuecomment-1875843052_

**Comment by Badaryman** [comment]
i manage it to host the apj on deta or should i host it on vercel? 

this is the api btw
https://amvstrmapiprod-1-y3870876.deta.app/

**Comment by Kenimarru** [comment]
Ill update the README file with the vercel deployment, be patient

**Comment by Badaryman** [comment]
okay thank you pleass include where to change the api i want to use the api i just hosted

**Comment by Kenimarru** [comment]
i added the vercel deployment button, after deploying make sure to update the environment variables by going to the repo deployment settings. you can find an example of the .env [here](https://github.com/Kenimarru/hiruki/blob/master/.env.example)

**Comment by Badaryman** [comment]
https://amvstrmapiprod-1-y3870876.deta.app/

where do i put this?

**Comment by Badaryman** [comment]
![Screenshot_2024-01-04-03-38-53-804_com android chrome](https://github.com/Kenimarru/hiruki/assets/154390732/04f49162-f611-49fe-8368-07532b95f3c1)
like this?

**Comment by Kenimarru** [comment]
I tested your deployed api and there is an issue with it idk what is it but it's not working, if you read the docs of [amvstrm api](https://docs.amvstr.me/api/introduction), you can use their api https://api.amvstr.me/, and about where do you put it here's how:
1- https://prnt.sc/jJBCQvuNyUc1
2- https://prnt.sc/4xTR1T_VxV8l
3- https://prnt.sc/ti6jTHm8lC6U

**Comment by Kenimarru** [comment]
if it's same not woring after updating the environment variables on vercel, you may need to redeploy

**Comment by Badaryman** [comment]
https://anime-fawn-sigma.vercel.app/

**Comment by Badaryman** [comment]
![Screenshot_2024-01-04-04-02-36-357_com android chrome](https://github.com/Kenimarru/hiruki/assets/154390732/7a924440-a2f4-4e9d-89ff-750a33d80819)
![Screenshot_2024-01-04-04-02-46-463_com android chrome](https://github.com/Kenimarru/hiruki/assets/154390732/c7945e6b-e626-4573-bc44-5b3917639842)

**Comment by Kenimarru** [comment]
That's weird i tried the same thing and it's running https://hiruki-cloned.vercel.app/

**Comment by Badaryman** [comment]
![Screenshot_2024-01-04-04-09-18-077_com android chrome](https://github.com/Kenimarru/hiruki/assets/154390732/0434c737-4bef-4f48-92bc-60c59d951a58)

like this right?

**Comment by Kenimarru** [comment]
there's nothing related to repo's .env file cause we are ignoring it on the .gitignore file, so only vercel's env is important

**Comment by Kenimarru** [comment]
oh, did you redeploy it?

**Comment by Badaryman** [comment]
yes still same issue

**Comment by Kenimarru** [comment]
is it working locally?

**Comment by Badaryman** [comment]
https://github.com/Badaryman/anime

check if there is somethinh wrong

**Comment by Badaryman** [comment]
> is it working locally?

yup

**Comment by Kenimarru** [comment]
update the .env file with this

VITE_API_V1=https://api.amvstr.me/api/v1
VITE_API_V2=https://api.amvstr.me/api/v2

**Comment by Badaryman** [comment]
https://anime-fawn-sigma.vercel.app/

**Comment by Badaryman** [comment]
check now

**Comment by Kenimarru** [comment]
Yea i saw, it's working now

**Comment by Badaryman** [comment]
thanks a lot

**Comment by Badaryman** [comment]
btw how will i know if it using v2 not v1?

**Comment by Kenimarru** [comment]
Hiruki uses both v1 and v2 cause some features aren't available in v2 so we used v1

**Comment by Badaryman** [comment]
i see thanks again

**Comment by Kenimarru** [comment]
No problem

**Comment by Badaryman** [comment]
the next step now is the api lol cant seem to host it on vercel

**Comment by Badaryman** [comment]
https://[api-self-eight.vercel.app](https://api-self-eight.vercel.app/)/

bro can you test this it seems when i click an episode i keeps on loading

**Comment by Badaryman** [comment]
@Kenimarru

**Comment by Kenimarru** [comment]
It seems like it's an issue with the api not with hiruki, cause when you fetch episodes from your deployed api the id value isn't there so it's returning undefined which causing the episodes not showing only loading state, here is a preview of the api response with no id value https://prnt.sc/ldEpNIA0qJUf

contact amvstrm api author for more info

**Comment by Badaryman** [comment]
thanks bro

**Comment by Badaryman** [comment]
bro it on v2 that has problem idk why 
@Kenimarru

**Comment by Kenimarru** [comment]
as i said contact amvstrm api author for more info, cause maybe you are deploying an old version of the api where the id isn't available or added yet

**Comment by Badaryman** [comment]
its now working now bro @Kenimarru

**Comment by Kenimarru** [comment]
That's great, enjoy
